/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateRoomIndexRouteImport } from './routes/create-room/index'
import { Route as RoomRoomIdRouteImport } from './routes/room/$roomId'
import { Route as RecordRoomAudioRoomIdRouteImport } from './routes/record-room-audio/$roomId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoomIndexRoute = CreateRoomIndexRouteImport.update({
  id: '/create-room/',
  path: '/create-room/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoomAudioRoomIdRoute = RecordRoomAudioRoomIdRouteImport.update({
  id: '/record-room-audio/$roomId',
  path: '/record-room-audio/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/record-room-audio/$roomId': typeof RecordRoomAudioRoomIdRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/create-room': typeof CreateRoomIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/record-room-audio/$roomId': typeof RecordRoomAudioRoomIdRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/create-room': typeof CreateRoomIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/record-room-audio/$roomId': typeof RecordRoomAudioRoomIdRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/create-room/': typeof CreateRoomIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/record-room-audio/$roomId'
    | '/room/$roomId'
    | '/create-room'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/record-room-audio/$roomId' | '/room/$roomId' | '/create-room'
  id:
    | '__root__'
    | '/'
    | '/record-room-audio/$roomId'
    | '/room/$roomId'
    | '/create-room/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecordRoomAudioRoomIdRoute: typeof RecordRoomAudioRoomIdRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
  CreateRoomIndexRoute: typeof CreateRoomIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-room/': {
      id: '/create-room/'
      path: '/create-room'
      fullPath: '/create-room'
      preLoaderRoute: typeof CreateRoomIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record-room-audio/$roomId': {
      id: '/record-room-audio/$roomId'
      path: '/record-room-audio/$roomId'
      fullPath: '/record-room-audio/$roomId'
      preLoaderRoute: typeof RecordRoomAudioRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecordRoomAudioRoomIdRoute: RecordRoomAudioRoomIdRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
  CreateRoomIndexRoute: CreateRoomIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
